version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog.api:
    image: catalog
    build:
      context: .\Services\ProductCatalogApi
      dockerfile: Dockerfile
    environment:
      - ConString=server=mssqlserver;Database=catalogDb;User Id=sa;Password=Jokoyoski200@
       
    ports: 
      - "5000:80"
    networks:
      - backend
      - frontend

    depends_on:
      - mssqlserver

  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
   
    environment:
      - SA_PASSWORD=MyProduct123!
      - ACCEPT_EULA=Y
    ports:
      - "1400:1433"
    
    container_name: mssqlcontainer

    networks:
      - backend
