version: "3.4"

networks:
  frontend:
  backend:

services:
  catalogService:
    image: catalog
    build:
      context: ./ProductCatalogApi
      dockerfile: Dockerfile
    
    container_name: catalog_container  
   
    ports: 
      - "5000:80"
    networks:
      - backend
      - frontend

    depends_on:
      - mssqlserverDb

  mssqlserverDb:
    image: microsoft/mssql-server-linux
   
    environment:
      - SA_PASSWORD=Jokoyoski200@
      - ACCEPT_EULA=Y
    ports:
      - "1400:1433"
    
    container_name: mssqlcontainer

    networks:
      - backend
